// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantPOS.API.Data;

#nullable disable

namespace RestaurantPOS.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251209194659_AddPosDevices")]
    partial class AddPosDevices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestaurantPOS.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Các món ăn",
                            Name = "Đồ ăn"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Các loại đồ uống",
                            Name = "Đồ uống"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Các món tráng miệng",
                            Name = "Tráng miệng"
                        });
                });

            modelBuilder.Entity("RestaurantPOS.API.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OrderGroupId")
                        .HasColumnType("int");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ParentOrderId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PaymentStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TableId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TableId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RestaurantPOS.API.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("RestaurantPOS.API.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("RestaurantPOS.API.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("RestaurantPOS.API.Models.PaymentSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BankBin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PaymentSettings");
                });

            modelBuilder.Entity("RestaurantPOS.API.Models.PosDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConnectionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceIdentifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastConnected")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PosDevices");
                });

            modelBuilder.Entity("RestaurantPOS.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("RestaurantPOS.API.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Floor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMerged")
                        .HasColumnType("bit");

                    b.Property<int?>("MergedGroupId")
                        .HasColumnType("int");

                    b.Property<string>("MergedTableNumbers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OccupiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TableNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 4,
                            Floor = "Tầng 1",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B01"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 4,
                            Floor = "Tầng 1",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B02"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 4,
                            Floor = "Tầng 1",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B03"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 4,
                            Floor = "Tầng 1",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B04"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 4,
                            Floor = "Tầng 1",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B05"
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 4,
                            Floor = "Tầng 1",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B06"
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 4,
                            Floor = "Tầng 1",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B07"
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 4,
                            Floor = "Tầng 1",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B08"
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 4,
                            Floor = "Tầng 1",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B09"
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 4,
                            Floor = "Tầng 1",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B10"
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 4,
                            Floor = "Tầng 1",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B11"
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 4,
                            Floor = "Tầng 1",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B12"
                        },
                        new
                        {
                            Id = 13,
                            Capacity = 4,
                            Floor = "Tầng 1",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B13"
                        },
                        new
                        {
                            Id = 14,
                            Capacity = 4,
                            Floor = "Tầng 1",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B14"
                        },
                        new
                        {
                            Id = 15,
                            Capacity = 4,
                            Floor = "Tầng 1",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B15"
                        },
                        new
                        {
                            Id = 16,
                            Capacity = 4,
                            Floor = "Tầng 1",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B16"
                        },
                        new
                        {
                            Id = 17,
                            Capacity = 4,
                            Floor = "Tầng 1",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B17"
                        },
                        new
                        {
                            Id = 18,
                            Capacity = 4,
                            Floor = "Tầng 1",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B18"
                        },
                        new
                        {
                            Id = 19,
                            Capacity = 4,
                            Floor = "Tầng 1",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B19"
                        },
                        new
                        {
                            Id = 20,
                            Capacity = 4,
                            Floor = "Tầng 1",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B20"
                        },
                        new
                        {
                            Id = 21,
                            Capacity = 6,
                            Floor = "Tầng 1",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B21"
                        },
                        new
                        {
                            Id = 22,
                            Capacity = 6,
                            Floor = "Tầng 1",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B22"
                        },
                        new
                        {
                            Id = 23,
                            Capacity = 6,
                            Floor = "Tầng 1",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B23"
                        },
                        new
                        {
                            Id = 24,
                            Capacity = 6,
                            Floor = "Tầng 1",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B24"
                        },
                        new
                        {
                            Id = 25,
                            Capacity = 6,
                            Floor = "Tầng 1",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B25"
                        },
                        new
                        {
                            Id = 26,
                            Capacity = 2,
                            Floor = "Tầng 1",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B26"
                        },
                        new
                        {
                            Id = 27,
                            Capacity = 2,
                            Floor = "Tầng 1",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B27"
                        },
                        new
                        {
                            Id = 28,
                            Capacity = 2,
                            Floor = "Tầng 1",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B28"
                        },
                        new
                        {
                            Id = 29,
                            Capacity = 2,
                            Floor = "Tầng 1",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B29"
                        },
                        new
                        {
                            Id = 30,
                            Capacity = 2,
                            Floor = "Tầng 1",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B30"
                        },
                        new
                        {
                            Id = 31,
                            Capacity = 4,
                            Floor = "Tầng 2",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B31"
                        },
                        new
                        {
                            Id = 32,
                            Capacity = 4,
                            Floor = "Tầng 2",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B32"
                        },
                        new
                        {
                            Id = 33,
                            Capacity = 4,
                            Floor = "Tầng 2",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B33"
                        },
                        new
                        {
                            Id = 34,
                            Capacity = 4,
                            Floor = "Tầng 2",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B34"
                        },
                        new
                        {
                            Id = 35,
                            Capacity = 4,
                            Floor = "Tầng 2",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B35"
                        },
                        new
                        {
                            Id = 36,
                            Capacity = 4,
                            Floor = "Tầng 2",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B36"
                        },
                        new
                        {
                            Id = 37,
                            Capacity = 4,
                            Floor = "Tầng 2",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B37"
                        },
                        new
                        {
                            Id = 38,
                            Capacity = 4,
                            Floor = "Tầng 2",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B38"
                        },
                        new
                        {
                            Id = 39,
                            Capacity = 4,
                            Floor = "Tầng 2",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B39"
                        },
                        new
                        {
                            Id = 40,
                            Capacity = 4,
                            Floor = "Tầng 2",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B40"
                        },
                        new
                        {
                            Id = 41,
                            Capacity = 4,
                            Floor = "Tầng 2",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B41"
                        },
                        new
                        {
                            Id = 42,
                            Capacity = 4,
                            Floor = "Tầng 2",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B42"
                        },
                        new
                        {
                            Id = 43,
                            Capacity = 4,
                            Floor = "Tầng 2",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B43"
                        },
                        new
                        {
                            Id = 44,
                            Capacity = 4,
                            Floor = "Tầng 2",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B44"
                        },
                        new
                        {
                            Id = 45,
                            Capacity = 4,
                            Floor = "Tầng 2",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B45"
                        },
                        new
                        {
                            Id = 46,
                            Capacity = 6,
                            Floor = "Tầng 2",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B46"
                        },
                        new
                        {
                            Id = 47,
                            Capacity = 6,
                            Floor = "Tầng 2",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B47"
                        },
                        new
                        {
                            Id = 48,
                            Capacity = 6,
                            Floor = "Tầng 2",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B48"
                        },
                        new
                        {
                            Id = 49,
                            Capacity = 6,
                            Floor = "Tầng 2",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B49"
                        },
                        new
                        {
                            Id = 50,
                            Capacity = 6,
                            Floor = "Tầng 2",
                            IsAvailable = true,
                            IsMerged = false,
                            TableNumber = "B50"
                        });
                });

            modelBuilder.Entity("RestaurantPOS.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FcmToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 9, 19, 46, 58, 914, DateTimeKind.Utc).AddTicks(6893),
                            Email = "admin@restaurantpos.com",
                            FullName = "Administrator",
                            IsActive = true,
                            PasswordHash = "$2a$11$OGeYyUPEujx7LBSfLjrbueqpnjDoCuN1qPZFinEXirEUVZmE5ZBiu",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("RestaurantPOS.API.Models.UserDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserDevices");
                });

            modelBuilder.Entity("RestaurantPOS.API.Models.Order", b =>
                {
                    b.HasOne("RestaurantPOS.API.Models.Table", "Table")
                        .WithMany("Orders")
                        .HasForeignKey("TableId");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("RestaurantPOS.API.Models.OrderItem", b =>
                {
                    b.HasOne("RestaurantPOS.API.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantPOS.API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RestaurantPOS.API.Models.PasswordResetToken", b =>
                {
                    b.HasOne("RestaurantPOS.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RestaurantPOS.API.Models.Payment", b =>
                {
                    b.HasOne("RestaurantPOS.API.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RestaurantPOS.API.Models.Product", b =>
                {
                    b.HasOne("RestaurantPOS.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RestaurantPOS.API.Models.UserDevice", b =>
                {
                    b.HasOne("RestaurantPOS.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RestaurantPOS.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("RestaurantPOS.API.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("RestaurantPOS.API.Models.Table", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
