CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210100910_InitialCreate') THEN
    CREATE TABLE "Categories" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(50) NOT NULL,
        "Description" character varying(200),
        CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210100910_InitialCreate') THEN
    CREATE TABLE "PaymentSettings" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "BankName" character varying(100) NOT NULL,
        "BankBin" character varying(20) NOT NULL,
        "AccountNumber" character varying(50) NOT NULL,
        "AccountName" character varying(100) NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "UpdatedByUserId" integer,
        CONSTRAINT "PK_PaymentSettings" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210100910_InitialCreate') THEN
    CREATE TABLE "PosDevices" (
        "Id" uuid NOT NULL,
        "Name" text NOT NULL,
        "DeviceIdentifier" text NOT NULL,
        "Type" text NOT NULL,
        "Status" text NOT NULL,
        "ConnectionType" text NOT NULL,
        "IpAddress" text NOT NULL,
        "RequestTime" timestamp with time zone NOT NULL,
        "LastConnected" timestamp with time zone,
        CONSTRAINT "PK_PosDevices" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210100910_InitialCreate') THEN
    CREATE TABLE "Tables" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "TableNumber" character varying(20) NOT NULL,
        "Capacity" integer NOT NULL,
        "IsAvailable" boolean NOT NULL,
        "OccupiedAt" timestamp with time zone,
        "Floor" character varying(50) NOT NULL,
        "IsMerged" boolean NOT NULL,
        "MergedGroupId" integer,
        "MergedTableNumbers" text,
        CONSTRAINT "PK_Tables" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210100910_InitialCreate') THEN
    CREATE TABLE "Users" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Username" character varying(100) NOT NULL,
        "Email" character varying(200) NOT NULL,
        "PasswordHash" text NOT NULL,
        "FullName" character varying(100) NOT NULL,
        "PhoneNumber" character varying(20),
        "Role" character varying(20) NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "LastLoginAt" timestamp with time zone,
        "FcmToken" character varying(500),
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210100910_InitialCreate') THEN
    CREATE TABLE "Products" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "Description" character varying(500),
        "Price" numeric(18,2) NOT NULL,
        "CategoryId" integer NOT NULL,
        "ImageUrl" text,
        "IsAvailable" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Products" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Products_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210100910_InitialCreate') THEN
    CREATE TABLE "Orders" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "TableId" integer,
        "OrderDate" timestamp with time zone NOT NULL,
        "TotalAmount" numeric(18,2) NOT NULL,
        "Status" character varying(20) NOT NULL,
        "CustomerName" text,
        "Notes" text,
        "OrderType" character varying(20) NOT NULL,
        "ParentOrderId" integer,
        "OrderGroupId" integer,
        "PaymentStatus" character varying(20),
        "PaymentMethod" character varying(20),
        "PaidAmount" numeric,
        "CompletedAt" timestamp with time zone,
        CONSTRAINT "PK_Orders" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Orders_Tables_TableId" FOREIGN KEY ("TableId") REFERENCES "Tables" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210100910_InitialCreate') THEN
    CREATE TABLE "PasswordResetTokens" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "Token" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "IsUsed" boolean NOT NULL,
        "UsedAt" timestamp with time zone,
        CONSTRAINT "PK_PasswordResetTokens" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PasswordResetTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210100910_InitialCreate') THEN
    CREATE TABLE "UserDevices" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "DeviceToken" text NOT NULL,
        "DeviceType" text,
        "LastUpdated" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_UserDevices" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_UserDevices_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210100910_InitialCreate') THEN
    CREATE TABLE "OrderItems" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrderId" integer NOT NULL,
        "ProductId" integer NOT NULL,
        "Quantity" integer NOT NULL,
        "UnitPrice" numeric(18,2) NOT NULL,
        "Notes" text,
        CONSTRAINT "PK_OrderItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_OrderItems_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_OrderItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210100910_InitialCreate') THEN
    CREATE TABLE "Payments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrderId" integer NOT NULL,
        "Amount" numeric NOT NULL,
        "Method" character varying(50) NOT NULL,
        "TransactionId" text,
        "Note" text,
        "PaymentDate" timestamp with time zone NOT NULL,
        "Status" character varying(20) NOT NULL,
        CONSTRAINT "PK_Payments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Payments_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210100910_InitialCreate') THEN
    INSERT INTO "Categories" ("Id", "Description", "Name")
    VALUES (1, 'Các món ăn', 'Đồ ăn');
    INSERT INTO "Categories" ("Id", "Description", "Name")
    VALUES (2, 'Các loại đồ uống', 'Đồ uống');
    INSERT INTO "Categories" ("Id", "Description", "Name")
    VALUES (3, 'Các món tráng miệng', 'Tráng miệng');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210100910_InitialCreate') THEN
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (1, 4, 'Tầng 1', TRUE, FALSE, NULL, NULL, NULL, 'B01');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (2, 4, 'Tầng 1', TRUE, FALSE, NULL, NULL, NULL, 'B02');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (3, 4, 'Tầng 1', TRUE, FALSE, NULL, NULL, NULL, 'B03');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (4, 4, 'Tầng 1', TRUE, FALSE, NULL, NULL, NULL, 'B04');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (5, 4, 'Tầng 1', TRUE, FALSE, NULL, NULL, NULL, 'B05');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (6, 4, 'Tầng 1', TRUE, FALSE, NULL, NULL, NULL, 'B06');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (7, 4, 'Tầng 1', TRUE, FALSE, NULL, NULL, NULL, 'B07');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (8, 4, 'Tầng 1', TRUE, FALSE, NULL, NULL, NULL, 'B08');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (9, 4, 'Tầng 1', TRUE, FALSE, NULL, NULL, NULL, 'B09');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (10, 4, 'Tầng 1', TRUE, FALSE, NULL, NULL, NULL, 'B10');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (11, 4, 'Tầng 1', TRUE, FALSE, NULL, NULL, NULL, 'B11');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (12, 4, 'Tầng 1', TRUE, FALSE, NULL, NULL, NULL, 'B12');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (13, 4, 'Tầng 1', TRUE, FALSE, NULL, NULL, NULL, 'B13');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (14, 4, 'Tầng 1', TRUE, FALSE, NULL, NULL, NULL, 'B14');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (15, 4, 'Tầng 1', TRUE, FALSE, NULL, NULL, NULL, 'B15');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (16, 4, 'Tầng 1', TRUE, FALSE, NULL, NULL, NULL, 'B16');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (17, 4, 'Tầng 1', TRUE, FALSE, NULL, NULL, NULL, 'B17');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (18, 4, 'Tầng 1', TRUE, FALSE, NULL, NULL, NULL, 'B18');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (19, 4, 'Tầng 1', TRUE, FALSE, NULL, NULL, NULL, 'B19');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (20, 4, 'Tầng 1', TRUE, FALSE, NULL, NULL, NULL, 'B20');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (21, 6, 'Tầng 1', TRUE, FALSE, NULL, NULL, NULL, 'B21');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (22, 6, 'Tầng 1', TRUE, FALSE, NULL, NULL, NULL, 'B22');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (23, 6, 'Tầng 1', TRUE, FALSE, NULL, NULL, NULL, 'B23');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (24, 6, 'Tầng 1', TRUE, FALSE, NULL, NULL, NULL, 'B24');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (25, 6, 'Tầng 1', TRUE, FALSE, NULL, NULL, NULL, 'B25');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (26, 2, 'Tầng 1', TRUE, FALSE, NULL, NULL, NULL, 'B26');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (27, 2, 'Tầng 1', TRUE, FALSE, NULL, NULL, NULL, 'B27');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (28, 2, 'Tầng 1', TRUE, FALSE, NULL, NULL, NULL, 'B28');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (29, 2, 'Tầng 1', TRUE, FALSE, NULL, NULL, NULL, 'B29');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (30, 2, 'Tầng 1', TRUE, FALSE, NULL, NULL, NULL, 'B30');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (31, 4, 'Tầng 2', TRUE, FALSE, NULL, NULL, NULL, 'B31');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (32, 4, 'Tầng 2', TRUE, FALSE, NULL, NULL, NULL, 'B32');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (33, 4, 'Tầng 2', TRUE, FALSE, NULL, NULL, NULL, 'B33');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (34, 4, 'Tầng 2', TRUE, FALSE, NULL, NULL, NULL, 'B34');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (35, 4, 'Tầng 2', TRUE, FALSE, NULL, NULL, NULL, 'B35');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (36, 4, 'Tầng 2', TRUE, FALSE, NULL, NULL, NULL, 'B36');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (37, 4, 'Tầng 2', TRUE, FALSE, NULL, NULL, NULL, 'B37');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (38, 4, 'Tầng 2', TRUE, FALSE, NULL, NULL, NULL, 'B38');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (39, 4, 'Tầng 2', TRUE, FALSE, NULL, NULL, NULL, 'B39');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (40, 4, 'Tầng 2', TRUE, FALSE, NULL, NULL, NULL, 'B40');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (41, 4, 'Tầng 2', TRUE, FALSE, NULL, NULL, NULL, 'B41');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (42, 4, 'Tầng 2', TRUE, FALSE, NULL, NULL, NULL, 'B42');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (43, 4, 'Tầng 2', TRUE, FALSE, NULL, NULL, NULL, 'B43');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (44, 4, 'Tầng 2', TRUE, FALSE, NULL, NULL, NULL, 'B44');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (45, 4, 'Tầng 2', TRUE, FALSE, NULL, NULL, NULL, 'B45');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (46, 6, 'Tầng 2', TRUE, FALSE, NULL, NULL, NULL, 'B46');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (47, 6, 'Tầng 2', TRUE, FALSE, NULL, NULL, NULL, 'B47');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (48, 6, 'Tầng 2', TRUE, FALSE, NULL, NULL, NULL, 'B48');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (49, 6, 'Tầng 2', TRUE, FALSE, NULL, NULL, NULL, 'B49');
    INSERT INTO "Tables" ("Id", "Capacity", "Floor", "IsAvailable", "IsMerged", "MergedGroupId", "MergedTableNumbers", "OccupiedAt", "TableNumber")
    VALUES (50, 6, 'Tầng 2', TRUE, FALSE, NULL, NULL, NULL, 'B50');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210100910_InitialCreate') THEN
    INSERT INTO "Users" ("Id", "CreatedAt", "Email", "FcmToken", "FullName", "IsActive", "LastLoginAt", "PasswordHash", "PhoneNumber", "Role", "Username")
    VALUES (1, TIMESTAMPTZ '2025-12-10T10:09:10.251775Z', 'admin@restaurantpos.com', NULL, 'Administrator', TRUE, NULL, '$2a$11$0ZtSK1yPTeAKk2T2n9Lpzu80gR.XdEAeSWG8OBK1rciibimMNfba.', NULL, 'Admin', 'admin');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210100910_InitialCreate') THEN
    CREATE INDEX "IX_OrderItems_OrderId" ON "OrderItems" ("OrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210100910_InitialCreate') THEN
    CREATE INDEX "IX_OrderItems_ProductId" ON "OrderItems" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210100910_InitialCreate') THEN
    CREATE INDEX "IX_Orders_TableId" ON "Orders" ("TableId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210100910_InitialCreate') THEN
    CREATE INDEX "IX_PasswordResetTokens_Token" ON "PasswordResetTokens" ("Token");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210100910_InitialCreate') THEN
    CREATE INDEX "IX_PasswordResetTokens_UserId" ON "PasswordResetTokens" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210100910_InitialCreate') THEN
    CREATE INDEX "IX_Payments_OrderId" ON "Payments" ("OrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210100910_InitialCreate') THEN
    CREATE INDEX "IX_Products_CategoryId" ON "Products" ("CategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210100910_InitialCreate') THEN
    CREATE INDEX "IX_UserDevices_UserId" ON "UserDevices" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210100910_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210100910_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Users_Username" ON "Users" ("Username");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210100910_InitialCreate') THEN
    PERFORM setval(
        pg_get_serial_sequence('"Categories"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Categories") + 1,
            nextval(pg_get_serial_sequence('"Categories"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"Tables"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Tables") + 1,
            nextval(pg_get_serial_sequence('"Tables"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"Users"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Users") + 1,
            nextval(pg_get_serial_sequence('"Users"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210100910_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251210100910_InitialCreate', '9.0.0');
    END IF;
END $EF$;
COMMIT;

