usecaseDiagram
    actor "Staff" as User
    actor "Hệ Thống Ngân Hàng" as Bank

    package "Module: Thanh Toán (Payment)" {
        usecase "Yêu Cầu Thanh Toán" as RequestPay
        usecase "In Tạm Tính" as PrintPreCheck
        usecase "Chọn Phương Thức TT" as SelectMethod
        
        usecase "Thanh Toán Tiền Mặt" as PayCash
        usecase "Thanh Toán QR Code" as PayQR
        
        usecase "Tạo Mã QR (VietQR)" as GenQR
        usecase "Xác Nhận Đã Nhận Tiền" as ConfirmPay
        usecase "In Hóa Đơn (Receipt)" as PrintBill
        usecase "Hoàn Tất & Đóng Bàn" as CloseTable
    }

    User --> RequestPay
    RequestPay --> PrintPreCheck : include
    RequestPay --> SelectMethod
    
    SelectMethod <|-- PayCash
    SelectMethod <|-- PayQR
    
    PayQR --> GenQR : include
    GenQR --> Bank : "API VietQR"
    PayQR --> ConfirmPay : include
    
    PayCash --> ConfirmPay
    ConfirmPay --> PrintBill : include
    ConfirmPay --> CloseTable : include
