usecaseDiagram
    actor "Staff" as User

    package "Module: Quản Lý Bàn & Gọi Món" {
        usecase "Xem Sơ Đồ Bàn" as ViewTable
        usecase "Gộp Bàn" as MergeTable
        usecase "Tách Bàn" as SplitTable
        usecase "Bắt Đầu Phục Vụ" as OpenTable
        
        usecase "Tạo Đơn Hàng Mới" as CreateOrder
        usecase "Thêm Món Ăn" as AddItem
        usecase "Ghi Chú Món" as NoteItem
        usecase "Cập Nhật Số Lượng" as UpdateQty
        usecase "Gửi Bếp (SignalR)" as SendKitchen
    }

    User --> ViewTable
    User --> OpenTable
    User --> CreateOrder
    
    OpenTable ..> ViewTable : extends
    MergeTable ..> ViewTable : extends
    SplitTable ..> ViewTable : extends
    
    CreateOrder --> AddItem : include
    AddItem --> NoteItem : include
    AddItem --> UpdateQty : include
    CreateOrder --> SendKitchen : include
